### ISSUE TITLE
Création class Modal 

### ISSUE THREAD

**Issue by remyjerome** [sciences-u-lyon/twitter-like-teamone#1]
Bonjour, 
J'ai une question concernant la creation de la Class Modal permettant l'affichage de des Tweets dans une modal. Pour le moment mon code permet l'affichage de ces tweets dans une modal mais je ne passe pas par une Class, je le fait grace au fichier js displayTweet.js. Ce fichier gère l'intégralité de la mise en place de la modal grace a la fonction displayTweet() utilisée depuis index.js. L'ajout des event click sont fait directement dans ce fichier.  

J'ai crée le fichier Modal.js qui remplacera a termes le fichier displayTweet.js. Les event sur le click sont-ils attendus dans le fichier js comme dans le code en commentaire ligne 13 et 14 dans le fichier index.js ?

Lorsque j'utilise ma class Modal à la place du fichier displayTweet.js, tout les tweets sont affichés en modal dès le chargement de la place. Et je ne comprend pas pourquoi. Avez vous une piste pour me permettre de résoudre ce problème ?

Remy JEROME

**Comment by nicolaspayot** [comment]
Hello Remy,

Les événements `click` pour ouvrir chaque modal doivent bien être implémentés de la manière que tu l'as fait, c'est à dire pour chaque tweet, dans la boucle `forEach`. Par contre, la gestion de l'événement `click` qui sert à fermer la modal a + sa place dans la classe `Modal`, dans le constructeur. Ajoute ce _click listener_ sur la div de background, celle qui a la classe `modal-overlay`.

Voila pourquoi toutes tes modales se chargent simultanément : 
```javascript
tweet.addEventListener('click', mod.open());
```
`addEventListener` exécute immédiatement la fonction passée en deuxième argument, du coup, ici : `mod.open()`. Il faut donc placer ce code dans une fonction : 

```javascript
tweet.addEventListener('click', function () {
  mod.open();
});
```

(ce que tu as fait dans `displayTweets.js` ligne 20)

Aussi, je te conseille d'instancier chaque modal dans le _click listener_, pour qu'elle soit créée au moment du click seulement.

---
Good job 👍 😉

**Comment by remyjerome** [comment]
Merci pour ces infos, j'ai modifié le code en conséquence. (cf. last `commit` https://github.com/sciences-u-lyon/twitter-like-teamone/commit/b889209da97998334a9437820ba179aa49a5b644)

Une class `Modal.js` permet désormais d'ouvrir/fermer les tweets. Néanmoins, si j'ai bien compris vôtre dernière réponse, vous me demandez de créer l'évent `click` qui sert à fermer la modal dans le constructeur de `Modal.js`. Pourquoi le faire dans le constructeur ? Personnellement je le fais dans la fonction `close()` comme ci-dessous :
```js
close() {
    return new Promise((resolve, reject) => {
      if ( this.display ) {
        document.querySelector(".modal-overlay").addEventListener('click', function() {
          document.querySelector(".modal-overlay").remove()
          setTimeout( () => { resolve(this.display?this.display = false:this.display = true)
          }, 100)//end setTimeout
        })//end addEventListener
      }//end if
    })//end return
  }//end close()
```

**Comment by nicolaspayot** [comment]
La solution que tu as utilisé est intéressante ! Bien qu'un petit peu _overkill_ je pense 😉 

En faisant de la façon suivante, l'utilisation des promesses et du flag `display` peuvent être évités : 
```javascript
constructor(tweet) {
  const template = `
    <div class="modal-content">
      <div class="tweet is-modal">
        ${tweet.outerHTML}
      </div>
    </div>
  `;
  this.tweetElement = document.createElement('div');
  this.tweetElement.className = 'modal-overlay';
  this.tweetElement.innerHTML = template;

  this.tweetElement.addEventListener('click', () => {
    this.close();
  });
}

open() {
  document.body.appendChild(this.tweetElement);
}

close() {
  document.querySelector('.modal-overlay').remove();
}
```
